### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by drcassar** [captain-pool/levenberg_marquardt#1]
Hi @captain-pool, I'm looking for a torch implementation of the LM optimizer and found your repository. I'm wondering what is the license of your code. Thanks.

**Comment by captain-pool** [comment]
The code needs some polishing. This doesn't use SVD based pseudo-inverse. I wrote it sometime ago. For small scale purposes only.

But feel free to make changes based on your needs. If you think your changes would help others too, feel free to create pull request to improve this one. :)

Other than that, you are free to use this codebase in anyway deemed necessary, as long as you cite this source.

**Comment by drcassar** [comment]
Thanks a lot! I want to use it to train dense MLPs with one or two hidden layers (for regression problems, no more than 128 neurons per layer). Do you think this scenario would fit in "small scale purposes"?

**Comment by captain-pool** [comment]
I think you should try and find out. The reason I mentioned "small scale",
is because LM Optimizer depends on calculating the jacobian for hessian
approximation. And this jacobian is mostly zeros. So, I was trying to make
it sparse. However I was not aware of the method to calculate a proper
pseudo inverse with an added noise for sparse tensors. So, instead of that,
I took the regular inverse. This takes the most time as it depends on the
number of trainable variables.

So I'm not sure how it would perform in your use case, but feel free to try
it out.

Also, If you can think of a way to improve it, please do make a pull
request.

**Comment by drcassar** [comment]
Sure thing, thanks!
